import React from 'react';
import { Link } from 'react-router-dom';
import { 
  FileSpreadsheet, 
  Brain, 
  BarChart3, 
  CheckCircle, 
  ArrowRight,
  Users,
  Award,
  Clock
} from 'lucide-react';
import Button from '../components/UI/Button';
import Card from '../components/UI/Card';

const HomePage = () => {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Get personalized Excel questions generated by advanced AI based on your experience level and target role.',
      color: 'text-blue-500'
    },
    {
      icon: BarChart3,
      title: 'Detailed Analysis',
      description: 'Receive comprehensive feedback on your Excel skills with specific strengths and improvement areas.',
      color: 'text-green-500'
    },
    {
      icon: Award,
      title: 'Professional Reports',
      description: 'Get a detailed assessment report suitable for sharing with potential employers.',
      color: 'text-purple-500'
    },
    {
      icon: Clock,
      title: 'Real-time Feedback',
      description: 'Instant evaluation of your answers with immediate feedback to accelerate your learning.',
      color: 'text-orange-500'
    }
  ];

  const stats = [
    // { label: 'Interviews Conducted', value: '10,000+', icon: Users },
    // { label: 'AI Questions Delivered', value: '100,000+', icon: Brain },
    { label: 'Average Interview Duration', value: '30 mins', icon: Clock },
    { label: 'User Satisfaction', value: '95%', icon: CheckCircle },
    // { label: 'Success Rate', value: '85%', icon: CheckCircle },
    { label: 'Average Score Improvement', value: '30%', icon: BarChart3 },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 via-white to-green-50 py-20 px-4">
        <div className="max-w-7xl mx-auto text-center">
          <div className="mb-8">
            <FileSpreadsheet className="h-16 w-16 text-green-600 mx-auto mb-4" />
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Master Excel with
              <span className="text-green-600"> AI-Powered </span>
              Mock Interviews
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Prepare for your Excel interviews with personalized AI-generated questions, 
              real-time feedback, and comprehensive skill assessments tailored to your experience level.
            </p>
          </div>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
            <Link to="/setup">
              <Button size="lg" className="w-full sm:w-auto">
                Start Your Interview
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Button variant="outline" size="lg" className="w-full sm:w-auto">
              Learn More
            </Button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            {stats.map((stat, index) => {
              const Icon = stat.icon;
              return (
                <Card key={index} className="p-6 text-center">
                  <Icon className="h-8 w-8 text-green-600 mx-auto mb-2" />
                  <div className="text-2xl font-bold text-gray-900 mb-1">
                    {stat.value}
                  </div>
                  <div className="text-sm text-gray-600">{stat.label}</div>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Why Choose Our Platform?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI-powered system provides the most comprehensive Excel interview 
              preparation experience available.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <Card key={index} className="p-6 text-center hover:shadow-lg transition-shadow" hover>
                  <Icon className={`h-12 w-12 ${feature.color} mx-auto mb-4`} />
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="py-20 px-4 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600">
              Get started in just three simple steps
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-blue-600">1</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                Setup Your Profile
              </h3>
              <p className="text-gray-600">
                Tell us about your experience level, target role, and areas of interest 
                to get personalized questions.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-green-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-green-600">2</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                Take the Interview
              </h3>
              <p className="text-gray-600">
                Answer AI-generated Excel questions tailored to your profile with 
                real-world scenarios and practical challenges.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-purple-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-purple-600">3</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">
                Get Your Report
              </h3>
              <p className="text-gray-600">
                Receive detailed feedback, skill assessment, and personalized 
                recommendations for improvement.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 bg-gradient-to-r from-green-600 to-blue-600">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Ready to Ace Your Excel Interview?
          </h2>
          <p className="text-xl text-green-100 mb-8">
            Join thousands of professionals who have improved their Excel skills 
            and landed their dream jobs.
          </p>
          <Link to="/setup">
            <Button size="xl" variant="secondary" className="bg-white text-green-600 hover:bg-gray-50">
              Start Your Free Interview Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>
      </section>
    </div>
  );
};

export default HomePage;